[package]
name = "math_traits"
version = "0.1.2"
authors = ["Sebastian Köln <sebk@rynx.org>"]
license = "MIT"
description = "traits to simplify vectorized mathematics"

[dependencies]
tuple = { git = "https://github.com/s3bk/tuple.git", features = ["impl_simd"] }
rand = "0.4.1"
simd = { version = "0.2.0", git = "https://github.com/s3bk/simd.git" }
