[package]
name = "math_traits"
version = "0.1.3"
authors = ["Sebastian Köln <sebk@rynx.org>"]
license = "MIT"
description = "traits to simplify vectorized mathematics"

[dependencies]
tuple = "0.3.8"
rand = "0.4.1"
stdsimd = {version = "0.0.4", optional = true}

[features]
simd = ["tuple/impl_simd", "stdsimd"]
