[package]
name = "math_traits"
version = "0.1.2"
authors = ["Sebastian Köln <sebk@rynx.org>"]
license = "MIT"
description = "traits to simplify vectorized mathematics"

[dependencies]
tuple = { git = "https://github.com/s3bk/tuple", features = ["impl_simd"] }
rand = "0.4.1"
stdsimd = { git = "https://github.com/rust-lang-nursery/stdsimd" }
